-- MySQL Script generated by MySQL Workbench
-- Thu Jan  9 16:18:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sys_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sys_permission` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sys_permission` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `premission_name` VARCHAR(45) NULL DEFAULT NULL COMMENT 'manu name',
  `premission_url` VARCHAR(100) NULL DEFAULT NULL COMMENT 'manu url',
  `parent_id` INT NOT NULL DEFAULT 0 COMMENT 'parent menu id',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sys_role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sys_role` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `ROLE_NAME` VARCHAR(45) NULL DEFAULT NULL COMMENT 'name of role',
  `ROLE_DESC` VARCHAR(60) NULL DEFAULT NULL COMMENT 'description of role',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `mydb`.`sys_role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sys_role_permission` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sys_role_permission` (
  `RID` INT NOT NULL COMMENT 'role id',
  `PID` INT NOT NULL COMMENT 'permission id',
  INDEX `fk_sys_role_permission_sys_permission_idx` (`PID` ASC),
  PRIMARY KEY (`RID`, `PID`),
  INDEX `fk_sys_role_permission_sys_role1_idx` (`RID` ASC),
  CONSTRAINT `fk_sys_role_permission_sys_permission`
    FOREIGN KEY (`PID`)
    REFERENCES `mydb`.`sys_permission` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_role_permission_sys_role1`
    FOREIGN KEY (`RID`)
    REFERENCES `mydb`.`sys_role` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `icon` BLOB NULL,
  `join_date` DATE NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `fk_Project_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Project_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Resource` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Resource` (
  `resource_id` INT NOT NULL AUTO_INCREMENT,
  `resource_code` VARCHAR(45) NULL,
  `resource_name` VARCHAR(45) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`resource_id`),
  INDEX `fk_Resource_Category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_Resource_Category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`Category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proj_res_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proj_res_mapping` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proj_res_mapping` (
  `project_id` INT NOT NULL,
  `resource_id` INT NOT NULL,
  INDEX `fk_pro_res_mapping_Project1_idx` (`project_id` ASC),
  INDEX `fk_pro_res_mapping_Resource1_idx` (`resource_id` ASC),
  PRIMARY KEY (`project_id`, `resource_id`),
  CONSTRAINT `fk_pro_res_mapping_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`Project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pro_res_mapping_Resource1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `mydb`.`Resource` (`resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cols` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cols` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `resource_id` INT NOT NULL,
  `field` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `formula` VARCHAR(45) NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_add_cols_proj_res_mapping1_idx` (`project_id` ASC, `resource_id` ASC),
  CONSTRAINT `fk_add_cols_proj_res_mapping1`
    FOREIGN KEY (`project_id` , `resource_id`)
    REFERENCES `mydb`.`proj_res_mapping` (`project_id` , `resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
