SELECT * FROM KoreraDB.user;
SELECT * FROM KoreraDB.project;
SELECT * FROM KoreraDB.resource;
SELECT * FROM KoreraDB.category;
SELECT * FROM KoreraDB.project_resource;
SELECT * FROM KoreraDB.cols;
SELECT * FROM KoreraDB.sys_role;
SELECT * FROM KoreraDB.sys_user_role;
SELECT * FROM KoreraDB.persistent_logins;
